# Generated by Django 5.0.3 on 2024-12-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_sub_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_tasks',
            field=models.JSONField(default=[]),
        ),
    ]
