# Generated by Django 5.0.3 on 2024-12-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_sub_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_done',
            field=models.JSONField(default=list),
        ),
    ]
