# Generated by Django 5.0.3 on 2024-12-13 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_sub_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bar', models.BooleanField(default=True)),
                ('bar_filter', models.TextField(default='1')),
                ('graphic', models.BooleanField(default=True)),
                ('task_filter', models.TextField(default='1')),
                ('task_color', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Preferance',
        ),
    ]
